import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Heal poiny service',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div>{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;