import Header from '@/components/Header/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import localFont from '@next/font/local';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Heal poiny service',
  description: 'Generated by create next app',
};
const gelica = localFont({
  src: [
    {
      path: '../../public/fonts/Fontspring-DEMO-gelica-medium.otf',
      weight: '500',
    },
    {
      path: '../../public/fonts/Fontspring-DEMO-gelica-bold.otf',
      weight: '700',
    },
    {
      path: '../../public/fonts/Fontspring-DEMO-gelica-semibold.otf',
      weight: '600',
    },
  ],
  variable: '--font-gelica',
});

const RootLayout = ({ children }) => {
  return (
    <html
      lang='en'
      className={`${gelica.variable} font-gelica`}>
      <body className={inter.className}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
};

export default RootLayout;
